// <auto-generated />
using System;
using DiscoveryService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiscoveryService.Migrations
{
    [DbContext(typeof(DiscoveryDbContext))]
    partial class DiscoveryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiscoveryService.Domain.Entities.Destination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.PrimitiveCollection<int[]>("BestTravelMonths")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.ToTable("Destinations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AverageBudget = 3000m,
                            BestTravelMonths = new[] { 10, 11, 12, 1, 2, 3 },
                            City = "Munnar",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A serene hill station in Kerala known for sprawling tea plantations, misty mountains, and a cool, relaxed atmosphere.",
                            Tags = new[] { "nature", "relaxed", "hills", "tea plantations", "honeymoon" },
                            UpdatedAt = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AverageBudget = 3500m,
                            BestTravelMonths = new[] { 3, 4, 5, 6, 12, 1, 2 },
                            City = "Manali",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A popular Himalayan hill town in Himachal Pradesh offering adventure sports, snow-capped peaks, and vibrant markets.",
                            Tags = new[] { "adventure", "mountains", "snow", "trekking", "nightlife" },
                            UpdatedAt = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AverageBudget = 2800m,
                            BestTravelMonths = new[] { 10, 11, 12, 1, 2, 3 },
                            City = "Coorg",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A lush coffee-growing district in Karnataka known as the 'Scotland of India', with waterfalls, forests, and a laid-back pace.",
                            Tags = new[] { "nature", "coffee", "relaxed", "waterfalls", "honeymoon" },
                            UpdatedAt = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            AverageBudget = 2500m,
                            BestTravelMonths = new[] { 4, 5, 6, 9, 10, 11 },
                            City = "Ooty",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A colonial-era hill station in the Nilgiris known for tea estates, botanical gardens, and pleasant year-round weather.",
                            Tags = new[] { "nature", "hills", "family", "gardens", "relaxed" },
                            UpdatedAt = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
