@IdentityService_HostAddress = http://localhost:5000

POST {{IdentityService_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "email": "jane.doe@example.com",
  "password": "SuperSecret123!"
}

###

POST {{IdentityService_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "jane.doe@example.com",
  "password": "SuperSecret123!"
}

###

GET {{IdentityService_HostAddress}}/api/auth/me
Authorization: Bearer {{accessToken}}

###
