import { formatPlanMoney, formatRequestedBudget } from "../format";
import type { TripPlanRequest, TripPlanResponse } from "../types";
import { PlanDay } from "./PlanDay";

// A stateless preview of AI output. It is never saved, and nothing here
// asserts that the plan fits the requested budget or matches the requested
// destination - both are shown exactly as returned, side by side.
export function GeneratedPlan({
  plan,
  request,
  onChangeRequest,
  onGenerateAnother,
}: {
  plan: TripPlanResponse;
  request: TripPlanRequest;
  onChangeRequest: () => void;
  onGenerateAnother: () => void;
}) {
  return (
    <section>
      <div className="preview-banner" role="status">
        <strong>Generated preview — not saved to your trips</strong>
        <p>
          This plan was generated by AI and is not saved anywhere. It disappears when you leave or refresh this page.
          Saving generated plans to My Trips isn't available yet.
        </p>
      </div>

      <article className="trip-details">
        <header className="trip-details-header">
          <div>
            <p className="eyebrow">Destination (as generated by AI)</p>
            <h2>{plan.destination}</h2>
          </div>
          <div className="trip-details-actions">
            <button type="button" className="btn" onClick={onChangeRequest}>
              Change request
            </button>
            <button type="button" className="btn btn-primary" onClick={onGenerateAnother}>
              Generate another plan
            </button>
          </div>
        </header>

        <p className="destination-description-full">{plan.summary}</p>

        <dl className="trip-details-facts">
          <div>
            <dt>Your requested total budget</dt>
            <dd>{formatRequestedBudget(request.budget)}</dd>
          </div>
          <div>
            <dt>AI estimated total</dt>
            <dd>{formatPlanMoney(plan.estimatedBudget, plan.currency)}</dd>
          </div>
          <div>
            <dt>Duration</dt>
            <dd>
              {plan.durationDays} day{plan.durationDays === 1 ? "" : "s"}
            </dd>
          </div>
          <div>
            <dt>Travelers</dt>
            <dd>{request.numberOfTravelers}</dd>
          </div>
        </dl>
        <p className="eyebrow">Costs are AI estimates, not guaranteed prices.</p>
      </article>

      <section className="itinerary">
        <div className="page-header">
          <h2>Day-by-day plan</h2>
        </div>
        {plan.days.map((day) => (
          <PlanDay key={day.day} day={day} currency={plan.currency} />
        ))}
      </section>

      {plan.recommendations.length > 0 && (
        <section className="dashboard-section">
          <h2>Recommendations</h2>
          <ul className="reasons">
            {plan.recommendations.map((item, index) => (
              <li key={index}>{item}</li>
            ))}
          </ul>
        </section>
      )}

      {plan.notes.length > 0 && (
        <section className="dashboard-section">
          <h2>Notes</h2>
          <ul className="reasons">
            {plan.notes.map((item, index) => (
              <li key={index}>{item}</li>
            ))}
          </ul>
        </section>
      )}
    </section>
  );
}
